ExportSelectedColumns/Sample/Controllers/CustomerController.cs
using AutoMapper;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Sample.Infrastructure.ActionResults;
using Sample.Infrastructure.Helpers;
using Sample.Infrastructure.ViewModels;
using Sample.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Sample.Controllers
{
    public class CustomerController : Controller
    {
        NorthwindDbContext db = new NorthwindDbContext();

        public ActionResult Index()
        {
            //匯出資料欄位
            var exportColumns =
                ExportColumnAttributeHelper<CustomerViewModel>.GetExportColumns()
                    .Select(c => new SelectListItem()
                    {
                        Value = c.ColumnName,
                        Text = c.Name,
                        Selected = true
                    })
                    .ToList();

            ViewBag.ExportColumns = exportColumns;

            //要匯出的資料
            var exportData = db.Customers.OrderBy(x => x.CustomerID).ToList();

            Mapper.CreateMap<Customer, CustomerViewModel>();
            var result = Mapper.Map<List<CustomerViewModel>>(exportData);

            return View(result);
        }

        [HttpPost]
        public ActionResult HasData()
        {
            JObject jo = new JObject();
            bool result = !db.Customers.Count().Equals(0);
            jo.Add("Msg", result.ToString());
            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }


        public ActionResult Export(string fileName, string selectedColumns)
        {
            //取得原始資料
            var exportData = db.Customers.OrderBy(x => x.CustomerID).ToList();

            //使用 AutoMapper 建立斷映轉換設定
            Mapper.CreateMap<Customer, CustomerViewModel>();

            //使用 AutoMapper 將 Customer 型別的原始資料對映轉換為 CustomerViewModel 型別.
            var result = Mapper.Map<List<CustomerViewModel>>(exportData);

            //使用轉換後的匯出資料與使用者所選的匯出欄位，產生作為匯出 Excel 的 DataTable.
            var dt = ExportDataHelper.GetExportDataTable(result, selectedColumns);

            //決定匯出 Excel 檔案的檔名
            var exportFileName = string.IsNullOrWhiteSpace(fileName)
                ? string.Concat(
                    "CustomerData_",
                    DateTime.Now.ToString("yyyyMMddHHmmss"),
                    ".xlsx")
                : string.Concat(fileName, ".xlsx");

            return new ExportExcelResult
            {
                SheetName = "客戶資料",
                FileName = exportFileName,
                ExportData = dt
            };
        }

    }

}

ExportSelectedColumns/Sample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sample.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ExportSelectedColumns/Sample/Controllers/ProductController.cs
using AutoMapper;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Sample.Infrastructure.ActionResults;
using Sample.Infrastructure.Helpers;
using Sample.Infrastructure.ViewModels;
using Sample.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Sample.Controllers
{
    public class ProductController : Controller
    {
        NorthwindDbContext db = new NorthwindDbContext();

        public ActionResult Index()
        {
            //匯出資料欄位
            var exportColumns =
                ExportColumnAttributeHelper<ProductViewModel>.GetExportColumns()
                    .Select(c => new SelectListItem()
                    {
                        Value = c.ColumnName,
                        Text = c.Name,
                        Selected = true
                    })
                    .ToList();

            ViewBag.ExportColumns = exportColumns;

            //要匯出的資料
            var exportData = db.Products.OrderBy(x => x.ProductID).ToList();

            Mapper.CreateMap<Product, ProductViewModel>()
                .ForMember(d => d.SupplierName, o => o.MapFrom(s => s.Supplier.CompanyName))
                .ForMember(d => d.CategoryName, o => o.MapFrom(s => s.Category.CategoryName))
                .ForMember(d => d.Discontinued, o => o.MapFrom(s => s.Discontinued ? "已停止" : "--"));

            var result = Mapper.Map<List<ProductViewModel>>(exportData);

            return View(result);
        }

        [HttpPost]
        public ActionResult HasData()
        {
            JObject jo = new JObject();
            bool result = !db.Products.Count().Equals(0);
            jo.Add("Msg", result.ToString());
            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }


        public ActionResult Export(string fileName, string selectedColumns)
        {
            //取得原始資料
            var exportData = db.Products.OrderBy(x => x.ProductID).ToList();

            //使用 AutoMapper 建立斷映轉換設定
            Mapper.CreateMap<Product, ProductViewModel>()
                .ForMember(d => d.SupplierName, o => o.MapFrom(s => s.Supplier.CompanyName))
                .ForMember(d => d.CategoryName, o => o.MapFrom(s => s.Category.CategoryName))
                .ForMember(d => d.Discontinued, o => o.MapFrom(s => s.Discontinued ? "已停止" : "--"));

            //使用 AutoMapper 將 Product 型別的原始資料對映轉換為 ProductViewModel 型別.
            var result = Mapper.Map<List<ProductViewModel>>(exportData);

            //使用轉換後的匯出資料與使用者所選的匯出欄位，產生作為匯出 Excel 的 DataTable.
            var dt = ExportDataHelper.GetExportDataTable(result, selectedColumns);

            //決定匯出 Excel 檔案的檔名
            var exportFileName = string.IsNullOrWhiteSpace(fileName)
                ? string.Concat(
                    "ProductData_",
                    DateTime.Now.ToString("yyyyMMddHHmmss"),
                    ".xlsx")
                : string.Concat(fileName, ".xlsx");

            return new ExportExcelResult
            {
                SheetName = "產品資料",
                FileName = exportFileName,
                ExportData = dt
            };
        }
    }

}

ExportSelectedColumns/Sample/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ExportSelectedColumns/Sample/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ExportSelectedColumns/Sample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET MVC</h1>
    <p class="lead">
        ASP.NET MVC 匯出 Excel - 讓使用者挑選要匯出的資料欄位
    </p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>匯出 Excel - Customers</h2>
        <p>
            Northwind - Customers            
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Customer")">Demo... &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>匯出 Excel - Products</h2>
        <p>
            Northwind - Products
        </p>
        <p>
            <a class="btn btn-default" href="@Url.Action("Index", "Product")">Demo... &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
    </div>
</div>      
<hr/>
<div class="row">
    <div class="col-md-12">
        <p>
            <a href="http://kevintsengtw.blogspot.tw/2014/09/aspnet-mvc-excel-excel.html" target="_blank">
                ASP.NET MVC 匯出 Excel 簡單做 - 自訂匯出 Excel 檔案的檔名
            </a>
        </p>     
        <p>
            <a href="http://kevintsengtw.blogspot.tw/2014/09/aspnet-mvc-excel-part1.html" target="_blank">
                ASP.NET MVC 匯出 Excel - 讓使用者挑選要匯出的資料欄位 Part.1
            </a>
        </p>
        <p>
            <a href="http://kevintsengtw.blogspot.tw/2014/10/aspnet-mvc-excel-part2.html" target="_blank">
                ASP.NET MVC 匯出 Excel - 讓使用者挑選要匯出的資料欄位 Part.2
            </a>
        </p>
        <p>
            <a href="http://kevintsengtw.blogspot.tw/2014/10/aspnet-mvc-excel-part3.html" target="_blank">
                ASP.NET MVC 匯出 Excel - 讓使用者挑選要匯出的資料欄位 Part.3
            </a>
        </p>
        <p>
            <a href="http://kevintsengtw.blogspot.tw/2014/10/aspnet-mvc-excel-part4.html" target="_blank">
                ASP.NET MVC 匯出 Excel - 讓使用者挑選要匯出的資料欄位 Part.4
            </a>
        </p>
    </div>
</div>